name: Exercise Check
on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  check-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        
     # - name: Install R packages
     #   run: Rscript -e "install.packages(c('your_package1', 'your_package2'), repos='https://cloud.r-project.org')"

      - name: Run R script
        run: Rscript script.r

      - name: Compare output
        run: |
          # Compare the actual output with the expected output
          diff - expected_output.txt

          # Check the diff exit code to determine if the outputs match
          if [ $? -eq 0 ]; then
            echo "Output matches the expected output."
          else
            echo "Output does not match the expected output."
            exit 1
          fi
